<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPWWBtz6\SimpleSAML_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPWWBtz6/SimpleSAML_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerPWWBtz6.legacy');

    return;
}

if (!\class_exists(SimpleSAML_KernelProdContainer::class, false)) {
    \class_alias(\ContainerPWWBtz6\SimpleSAML_KernelProdContainer::class, SimpleSAML_KernelProdContainer::class, false);
}

return new \ContainerPWWBtz6\SimpleSAML_KernelProdContainer([
    'container.build_hash' => 'PWWBtz6',
    'container.build_id' => 'b94645de',
    'container.build_time' => 1741679689,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPWWBtz6');
