<?php

// This file has been auto-generated by the Symfony Dependency Injection Component
// You can reference it in the "opcache.preload" php.ini setting on PHP >= 7.4 when preloading is desired

use Symfony\Component\DependencyInjection\Dumper\Preloader;

if (in_array(PHP_SAPI, ['cli', 'phpdbg', 'embed'], true)) {
    return;
}

require dirname(__DIR__, 2).''.\DIRECTORY_SEPARATOR.'vendor/autoload.php';
(require __DIR__.'/SimpleSAML_KernelProdContainer.php')->set(\ContainerJARJext\SimpleSAML_KernelProdContainer::class, null);
require __DIR__.'/ContainerJARJext/RequestPayloadValueResolverGhostC1069a2.php';
require __DIR__.'/ContainerJARJext/getServicesResetterService.php';
require __DIR__.'/ContainerJARJext/getSecrets_VaultService.php';
require __DIR__.'/ContainerJARJext/getHttpKernelService.php';
require __DIR__.'/ContainerJARJext/getErrorControllerService.php';
require __DIR__.'/ContainerJARJext/getDebug_ErrorHandlerConfiguratorService.php';
require __DIR__.'/ContainerJARJext/getContainer_GetRoutingConditionServiceService.php';
require __DIR__.'/ContainerJARJext/getContainer_EnvVarProcessorsLocatorService.php';
require __DIR__.'/ContainerJARJext/getContainer_EnvVarProcessorService.php';
require __DIR__.'/ContainerJARJext/getCache_SystemClearerService.php';
require __DIR__.'/ContainerJARJext/getCache_SystemService.php';
require __DIR__.'/ContainerJARJext/getCache_GlobalClearerService.php';
require __DIR__.'/ContainerJARJext/getCache_AppClearerService.php';
require __DIR__.'/ContainerJARJext/getCache_AppService.php';
require __DIR__.'/ContainerJARJext/getArgumentResolver_VariadicService.php';
require __DIR__.'/ContainerJARJext/getArgumentResolver_SessionService.php';
require __DIR__.'/ContainerJARJext/getArgumentResolver_ServiceService.php';
require __DIR__.'/ContainerJARJext/getArgumentResolver_RequestAttributeService.php';
require __DIR__.'/ContainerJARJext/getArgumentResolver_RequestService.php';
require __DIR__.'/ContainerJARJext/getArgumentResolver_QueryParameterValueResolverService.php';
require __DIR__.'/ContainerJARJext/getArgumentResolver_DefaultService.php';
require __DIR__.'/ContainerJARJext/getArgumentResolver_DatetimeService.php';
require __DIR__.'/ContainerJARJext/getArgumentResolver_BackedEnumResolverService.php';
require __DIR__.'/ContainerJARJext/getTemplateControllerService.php';
require __DIR__.'/ContainerJARJext/getRedirectControllerService.php';
require __DIR__.'/ContainerJARJext/getWebBrowserSingleSignOnService.php';
require __DIR__.'/ContainerJARJext/getSingleLogoutService.php';
require __DIR__.'/ContainerJARJext/getServiceProviderService.php';
require __DIR__.'/ContainerJARJext/getProxyService.php';
require __DIR__.'/ContainerJARJext/getMetadataService.php';
require __DIR__.'/ContainerJARJext/getDiscoService.php';
require __DIR__.'/ContainerJARJext/getConfigurationService.php';
require __DIR__.'/ContainerJARJext/get_ServiceLocator_Y4Zrx_Service.php';

$classes = [];
$classes[] = 'Symfony\Bundle\FrameworkBundle\FrameworkBundle';
$classes[] = 'Symfony\Component\DependencyInjection\ServiceLocator';
$classes[] = 'SimpleSAML\Configuration';
$classes[] = 'SimpleSAML\Module\saml\Controller\Disco';
$classes[] = 'SimpleSAML\Module\saml\Controller\Metadata';
$classes[] = 'SimpleSAML\Module\saml\Controller\Proxy';
$classes[] = 'SimpleSAML\Module\saml\Controller\ServiceProvider';
$classes[] = 'SimpleSAML\Session';
$classes[] = 'SimpleSAML\Module\saml\Controller\SingleLogout';
$classes[] = 'SimpleSAML\Module\saml\Controller\WebBrowserSingleSignOn';
$classes[] = 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController';
$classes[] = 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\BackedEnumValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\DateTimeValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\DefaultValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\QueryParameterValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestAttributeValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\SessionValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\VariadicValueResolver';
$classes[] = 'Symfony\Component\Cache\Adapter\FilesystemAdapter';
$classes[] = 'Symfony\Component\Cache\Marshaller\DefaultMarshaller';
$classes[] = 'Symfony\Component\HttpKernel\CacheClearer\Psr6CacheClearer';
$classes[] = 'Symfony\Component\Cache\Adapter\AdapterInterface';
$classes[] = 'Symfony\Component\Cache\Adapter\AbstractAdapter';
$classes[] = 'Symfony\Component\DependencyInjection\EnvVarProcessor';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\CacheAttributeListener';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\DebugHandlersListener';
$classes[] = 'Symfony\Component\HttpKernel\Debug\ErrorHandlerConfigurator';
$classes[] = 'Symfony\Component\ErrorHandler\ErrorRenderer\FileLinkFormatter';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ErrorController';
$classes[] = 'Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer';
$classes[] = 'Symfony\Component\EventDispatcher\EventDispatcher';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\ErrorListener';
$classes[] = 'Symfony\Component\HttpKernel\HttpKernel';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\ResponseListener';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ContainerControllerResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver';
$classes[] = 'Symfony\Component\HttpKernel\ControllerMetadata\ArgumentMetadataFactory';
$classes[] = 'SimpleSAML\Kernel';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\LocaleAwareListener';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\LocaleListener';
$classes[] = 'Symfony\Component\HttpKernel\Log\Logger';
$classes[] = 'Symfony\Component\HttpFoundation\RequestStack';
$classes[] = 'Symfony\Component\Routing\Router';
$classes[] = 'Symfony\Component\Routing\RequestContext';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\RouterListener';
$classes[] = 'Symfony\Component\Config\Loader\DelegatingLoader';
$classes[] = 'Symfony\Component\Config\Loader\LoaderResolver';
$classes[] = 'Symfony\Component\Routing\Loader\XmlFileLoader';
$classes[] = 'Symfony\Component\Config\FileLocator';
$classes[] = 'Symfony\Component\Routing\Loader\YamlFileLoader';
$classes[] = 'Symfony\Component\Routing\Loader\PhpFileLoader';
$classes[] = 'Symfony\Component\Routing\Loader\GlobFileLoader';
$classes[] = 'Symfony\Component\Routing\Loader\DirectoryLoader';
$classes[] = 'Symfony\Component\Routing\Loader\ContainerLoader';
$classes[] = 'Symfony\Bundle\FrameworkBundle\Routing\AttributeRouteControllerLoader';
$classes[] = 'Symfony\Component\Routing\Loader\AttributeDirectoryLoader';
$classes[] = 'Symfony\Component\Routing\Loader\AttributeFileLoader';
$classes[] = 'Symfony\Component\Routing\Loader\Psr4DirectoryLoader';
$classes[] = 'Symfony\Bundle\FrameworkBundle\Secrets\SodiumVault';
$classes[] = 'Symfony\Component\String\LazyString';
$classes[] = 'Symfony\Component\DependencyInjection\ContainerInterface';
$classes[] = 'Symfony\Component\HttpKernel\DependencyInjection\ServicesResetter';
$classes[] = 'Symfony\Component\String\Slugger\AsciiSlugger';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\ValidateRequestListener';

$preloaded = Preloader::preload($classes);
