<?php

namespace ContainerJARJext;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceProviderService extends SimpleSAML_KernelProdContainer
{
    /*
     * Gets the public 'SimpleSAML\Module\saml\Controller\ServiceProvider' shared autowired service.
     *
     * @return \SimpleSAML\Module\saml\Controller\ServiceProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['SimpleSAML\\Module\\saml\\Controller\\ServiceProvider'] = new \SimpleSAML\Module\saml\Controller\ServiceProvider(($container->privates['SimpleSAML\\Configuration'] ?? $container->load('getConfigurationService')), \SimpleSAML\Session::getSessionFromRequest());
    }
}
