<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerArsFhOf\SimpleSAML_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerArsFhOf/SimpleSAML_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerArsFhOf.legacy');

    return;
}

if (!\class_exists(SimpleSAML_KernelProdContainer::class, false)) {
    \class_alias(\ContainerArsFhOf\SimpleSAML_KernelProdContainer::class, SimpleSAML_KernelProdContainer::class, false);
}

return new \ContainerArsFhOf\SimpleSAML_KernelProdContainer([
    'container.build_hash' => 'ArsFhOf',
    'container.build_id' => 'e6140b70',
    'container.build_time' => 1741612849,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerArsFhOf');
