<?php

namespace ContainerArsFhOf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigurationService extends SimpleSAML_KernelProdContainer
{
    /*
     * Gets the private 'SimpleSAML\Configuration' shared service.
     *
     * @return \SimpleSAML\Configuration
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['SimpleSAML\\Configuration'] = \SimpleSAML\Configuration::getInstance();
    }
}
