<?php

namespace ContainerArsFhOf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getErrorReportService extends SimpleSAML_KernelProdContainer
{
    /*
     * Gets the public 'SimpleSAML\Module\core\Controller\ErrorReport' shared autowired service.
     *
     * @return \SimpleSAML\Module\core\Controller\ErrorReport
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['SimpleSAML\\Module\\core\\Controller\\ErrorReport'] = new \SimpleSAML\Module\core\Controller\ErrorReport(($container->privates['SimpleSAML\\Configuration'] ?? $container->load('getConfigurationService')), ($container->privates['SimpleSAML\\Session'] ?? $container->load('getSessionService')));
    }
}
