<?php

namespace ContainerArsFhOf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionService extends SimpleSAML_KernelProdContainer
{
    /*
     * Gets the private 'SimpleSAML\Session' shared service.
     *
     * @return \SimpleSAML\Session
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['SimpleSAML\\Session'] = \SimpleSAML\Session::getSessionFromRequest();
    }
}
